blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    
    path('', views.blog, name= 'Blog'),
    path('categoria/<int:categoria_id>/', views.categorias,name ='categoria'),
    
]

carro/urls.py
from django.urls import path
from . import views


app_name = "carro"
urlpatterns = [
    
    path('agregar/<int:producto_id>/',views.agregar_producto,name="agregar"),
    path('eliminar/<int:producto_id>/',views.eliminar_producto,name="eliminar"),
    path('restar/<int:producto_id>/',views.restar_producto,name="restar"),
    path('limpiar/',views.limpiar_carro,name="limpiar"),
    
    
]

projecto_web/urls.py
from unicodedata import name
from django.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',include('projecto_web_app.urls')),
    
    path('servicios/', include('servicios.urls')),

    path('blog/', include('blog.urls')),

    path('contacto/', include('contacto.urls')),

    path('tienda/', include('tienda.urls')),

    path('carro/', include('carro.urls')),

    path('autenticacion/', include('autenticacion.urls')),




    
]

tienda/urls.py
from django.urls import path
from . import views


urlpatterns = [
    
    path('',views.tienda, name='Tienda'),
    
    
    
    


]

tienda/models.py
from django.db import models

# Create your models here to create BD in SQLite
class categoriaProducto(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'categoriaProducto'
        verbose_name_plural = 'categoriasProducto'
    
    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    categorias = models.ForeignKey(categoriaProducto,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to = 'tienda', null = True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

carro/views.py
from django.shortcuts import render
from .carro import carro
from tienda.models import Producto
from django.shortcuts import redirect

# Create your views here.


# view to add items
def agregar_producto(request,producto_id):
    carroz = carro(request)

    producto = Producto.objects.get(id=producto_id)

    carroz.agregar(producto=producto)

    return redirect('Tienda')

# view to delete 1 product
def eliminar_producto(request,producto_id):
    carroz = carro(request)

    producto = Producto.objects.get(id=producto_id)

    carroz.eliminar(producto=producto)
    
    return redirect('Tienda')
    
#view to subtract
def restar_producto(request,producto_id):
    carroz = carro(request)

    producto = Producto.objects.get(id=producto_id)

    carroz.restar_producto(producto=producto)
    
    return redirect('Tienda')
#view to clean it
def limpiar_carro(request, producto_id):
    carroz = carro(request)

    carroz.limpiar_carro()

    return redirect('Tienda')

tienda/views.py
from django.shortcuts import render
from .models import Producto
# Create your views here.


def tienda(request):
    productos = Producto.objects.all()


    return render(request, 'tienda/tienda.html',{'productos':productos})

tienda/templates/carro/widget.html
<head>
    <style>
        .tablita{
            
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            -ms-border-radius: 5px;
            -o-border-radius: 5px;
            box-shadow: 5px 5px 5px 5px rgba(0, 0, 0, 0.6);
            
            margin-top: 2vh;
            background-color: rgb(24, 64, 8, 0.9); 
        }
    </style>
</head>
<div class="tablita" style="">
    <table class="table table-bordered table-responsive" style="color: white;">
        <thead>
            <tr>
                <td colspan="3" class="text-center">
                    Shopping
                </td>
            </tr>
            <tr>
                <td>Items</td>
                <td>Amount</td>
                <td>Mod</td>
            </tr>
        </thead>
        <tbody class="" style="overflow: scroll">
            {% if request.session.carro.items %}
                {% for key,value in request.session.carro.items %}
                    <tr class="text-center ">
                        <td>{{value.nombre}}</td>
                        <td>{{value.cantidad}}</td>
                        <td>
                            <a href="{% url 'carro:agregar' value.producto_id %}" class="btm btn-sm btn-success">+</a>
                            <a href="{% url 'carro:restar' value.producto_id %}" class="btm btn-sm btn-success">-</a><br>
                            
                            {{value.precio}}Є
                        </td>
                    </tr>

                {% endfor %}

            {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        Without items
                    </div>

                </td>
            </tr>
            {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">
                    Total: {{importe_total_carro}}Є
                    {% if importe_total_carro > 0 %}
                        
                        <input class="btm btn-sm btn-success" type="submit" value="Comprar" style="text-align: right;margin-left: 5vw;">
                        
                    {% endif %}
                </td>
            </tr>
            

        </tfoot>

    </table> 
</div>